### ISSUE TITLE
Add in ability to supress messages on loading

### ISSUE THREAD

**Issue by sjentoft** [DiegoZardetto/ReGenesees#1]
Hi. 
It seems it is not possible to suppress messages on loading the package. I have tried `suppressPackageStartupMessages()`
 , `suppressMessages()`, `suppressWarnings()` in addition to parameters `quiet=T` and `warn.conflicts = F`. 

Could you consider checking how this message is generated and adjusting it so that it can be suppressed?

**Comment by DiegoZardetto** [comment]
Hi Susie,
You are right, at the moment you cannot (entirely) suppress the messages that are printed when attaching ReGenesees.

Since adding the required feature is not entirely trivial, I would very much appreciate if you could concisely explain why and how, based on your user experience, the current messages are negatively affecting your work (especially considering that those messages provide information that I don't deem entirely useless).

Thank you,
D.

**Comment by sjentoft** [comment]
Thanks for your reply. It is of course not a big problem, and if it is a lot of work then we will work around it here. The main difficulty is when we are running checks and tests. As some of the functions in ReGenesees are used in production here (at Statistics Norway) we have a series of unittests that run automatically on various versions of R and systems for checking of functionality and new builds of R. These messages appear, and have caused some confusion on whether there were problems (which there weren't). Therefore an easy way to suppress the messages that we know can be ignored would be useful for us.

**Comment by DiegoZardetto** [comment]
Hi Susie,
Thanks for following up on this.

As soon as I find the time, I'll make an attempt to turn all the startup messages printed by ReGenesees to "suppressible" ones, so that Statistics Norway can manage to make them silent via suppressPackageStartupMessages().

Best,
D.

**Comment by DiegoZardetto** [comment]
The issue has been solved and no longer exists in the development version of ReGenesees 2.3.
D.
